# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    old_grp = ctx.current_group
    ctx.set_group('buildtools')
    try:
        ctx.py_module('__init__.py')
        ctx.py_module('build_model.py')
        ctx.py_proto('model_desc.proto')
    finally:
        ctx.set_group(old_grp)

    old_grp = ctx.current_group
    ctx.set_group('buildtools')
    try:
        ctx.py_module('profutil.py')
        ctx.py_module('perf_stats.py')
        ctx.py_module('qttest.py')
        ctx.py_module('unittest.py')
        ctx.py_module('unittest_mixins.py')
        ctx.py_module('unittest_processor_mixins.py')
        ctx.cy_module('unittest_engine_mixins.pyx', use=['LILV'])
        ctx.cy_module('unittest_engine_utils.pyx', use=['LILV'])
        ctx.py_module('uitest.py')
        ctx.py_module('demo_project.py')
    finally:
        ctx.set_group(old_grp)
