# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_module('profutil.py', mypy='loose')
    ctx.py_module('perf_stats.py', mypy='loose')
    ctx.py_module('qttest.py', mypy='loose')
    ctx.py_module('unittest.py', mypy='loose')
    ctx.py_module('unittest_mixins.py', mypy='loose')
    ctx.py_module('unittest_processor_mixins.py', mypy='loose')
    ctx.cy_module('unittest_engine_mixins.pyx',
                  use=['noisicaa-host_system', 'noisicaa-audioproc-engine'])
    ctx.cy_module('unittest_engine_utils.pyx',
                  use=['noisicaa-host_system', 'noisicaa-audioproc-engine'])
    ctx.py_module('uitest.py', mypy='loose')
    ctx.py_module('demo_project.py', mypy='loose')
    ctx.py_module('test_runner.py', mypy='loose')
