# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.model_description('model.desc.pb', template='noisicaa/music/model.py')

    ctx.py_module('__init__.py')
    ctx.py_module('base_track.py')
    ctx.py_test('base_track_test.py')
    ctx.py_module('graph.py')
    ctx.py_test('graph_test.py')
    ctx.py_module('metadata.py')
    ctx.py_module('model_base.py')
    ctx.py_test('model_base_test.py')
    ctx.py_module('mutations.py')
    ctx.py_module('node_connector.py')
    ctx.py_module('player.py')
    ctx.py_test('player_integration_test.py')
    ctx.py_test('player_test.py')
    ctx.py_module('project.py')
    ctx.py_module('project_client.py')
    ctx.py_test('project_client_test.py')
    ctx.py_test('project_integration_test.py')
    ctx.py_test('project_test.py')
    ctx.py_module('render.py')
    ctx.py_test('render_test.py')
    ctx.cy_module('rms.pyx')
    ctx.py_module('samples.py')
    ctx.py_module('session_value_store.py')
    ctx.py_module('transfer_function.py')
    ctx.py_test('transfer_function_test.py')
    ctx.py_module('writer_client.py')
    ctx.py_test('writer_client_test.py')
    ctx.py_module('writer_process.py')

    ctx.py_proto('model.proto')
    ctx.py_proto('project.proto')
    ctx.py_proto('model_base.proto')
    ctx.py_proto('model_base_test.proto')
    ctx.py_proto('writer_process.proto')
    ctx.py_proto('render.proto')
    ctx.py_proto('mutations.proto')
