# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_module('clef.py')
    ctx.py_module('color.py')
    ctx.py_module('control_value.py')
    ctx.py_module('key_signature.py')
    ctx.py_test('key_signature_test.py')
    ctx.py_module('midi_event.py')
    ctx.py_module('node_port_properties.py')
    ctx.py_module('pitch.py')
    ctx.py_test('pitch_test.py')
    ctx.py_module('pos2f.py')
    ctx.py_module('proto_value.py')
    ctx.py_module('sizef.py')
    ctx.py_module('time_signature.py')
    ctx.py_test('time_signature_test.py')
    ctx.py_proto('value_types.proto')
