# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_module('node_description_registry.py')
    ctx.py_module('ui_registry.py')
    ctx.py_module('model_registry.py')
    ctx.py_proto('model_registry.proto')
    ctx.py_proto('processor_message_registry.proto')

    ctx.cpp_proto('processor_message_registry.proto')

    # add_library(noisicaa-builtin_nodes-processor_message_registry SHARED processor_message_registry.pb.cc)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-audioproc-public)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-builtin_nodes-control_track-processor_messages)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-builtin_nodes-sample_track-processor_messages)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-builtin_nodes-instrument-processor_messages)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-builtin_nodes-pianoroll-processor_messages)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-builtin_nodes-midi_source-processor_messages)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-builtin_nodes-midi_cc_to_cv-processor_messages)
    # target_link_libraries(noisicaa-builtin_nodes-processor_message_registry PRIVATE noisicaa-builtin_nodes-midi_looper-processor_messages)

    # add_library(noisicaa-builtin_nodes-processors SHARED processor_registry.cpp)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-control_track-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-sample_track-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-instrument-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-pianoroll-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-mixer-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-custom_csound-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-midi_source-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-oscillator-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-vca-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-noise-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-step_sequencer-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-midi_cc_to_cv-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-midi_looper-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-midi_monitor-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-metronome-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-midi_velocity_mapper-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-cv_mapper-processor)
    # target_link_libraries(noisicaa-builtin_nodes-processors PRIVATE noisicaa-builtin_nodes-oscilloscope-processor)

    ctx.recurse('score_track')
    ctx.recurse('beat_track')
    ctx.recurse('control_track')
    ctx.recurse('sample_track')
    ctx.recurse('instrument')
    ctx.recurse('pianoroll')
    ctx.recurse('mixer')
    ctx.recurse('custom_csound')
    ctx.recurse('midi_source')
    ctx.recurse('oscillator')
    ctx.recurse('vca')
    ctx.recurse('noise')
    ctx.recurse('step_sequencer')
    ctx.recurse('midi_cc_to_cv')
    ctx.recurse('midi_looper')
    ctx.recurse('midi_monitor')
    ctx.recurse('metronome')
    ctx.recurse('midi_velocity_mapper')
    ctx.recurse('cv_mapper')
    ctx.recurse('oscilloscope')
