# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_module('node_description_registry.py')
    ctx.py_module('ui_registry.py')
    ctx.py_module('model_registry.py')
    ctx.py_proto('model_registry.proto')
    ctx.py_proto('processor_message_registry.proto')

    ctx.shlib(
        target='noisicaa-builtin_nodes-processor_message_registry',
        source=[
            ctx.cpp_proto('processor_message_registry.proto'),
        ],
        use=[
            'noisicaa-audioproc-public',
            'noisicaa-builtin_nodes-control_track-processor_messages',
            'noisicaa-builtin_nodes-sample_track-processor_messages',
            'noisicaa-builtin_nodes-instrument-processor_messages',
            'noisicaa-builtin_nodes-pianoroll-processor_messages',
            'noisicaa-builtin_nodes-midi_source-processor_messages',
            'noisicaa-builtin_nodes-midi_cc_to_cv-processor_messages',
            'noisicaa-builtin_nodes-midi_looper-processor_messages',
        ],
    )

    ctx.shlib(
        target='noisicaa-builtin_nodes-processors',
        source=[
            ctx.cpp_module('processor_registry.cpp'),
        ],
        use=[
            'noisicaa-builtin_nodes-control_track-processor',
            'noisicaa-builtin_nodes-sample_track-processor',
            'noisicaa-builtin_nodes-instrument-processor',
            'noisicaa-builtin_nodes-pianoroll-processor',
            'noisicaa-builtin_nodes-mixer-processor',
            'noisicaa-builtin_nodes-custom_csound-processor',
            'noisicaa-builtin_nodes-midi_source-processor',
            'noisicaa-builtin_nodes-oscillator-processor',
            'noisicaa-builtin_nodes-vca-processor',
            'noisicaa-builtin_nodes-noise-processor',
            'noisicaa-builtin_nodes-step_sequencer-processor',
            'noisicaa-builtin_nodes-midi_cc_to_cv-processor',
            'noisicaa-builtin_nodes-midi_looper-processor',
            'noisicaa-builtin_nodes-midi_monitor-processor',
            'noisicaa-builtin_nodes-metronome-processor',
            'noisicaa-builtin_nodes-midi_velocity_mapper-processor',
            'noisicaa-builtin_nodes-cv_mapper-processor',
            'noisicaa-builtin_nodes-oscilloscope-processor',
            'noisicaa-builtin_nodes-vumeter-processor',
        ],
    )

    ctx.recurse('score_track')
    ctx.recurse('beat_track')
    ctx.recurse('control_track')
    ctx.recurse('sample_track')
    ctx.recurse('pianoroll_track')
    ctx.recurse('instrument')
    ctx.recurse('pianoroll')
    ctx.recurse('mixer')
    ctx.recurse('custom_csound')
    ctx.recurse('midi_source')
    ctx.recurse('oscillator')
    ctx.recurse('vca')
    ctx.recurse('noise')
    ctx.recurse('step_sequencer')
    ctx.recurse('midi_cc_to_cv')
    ctx.recurse('midi_looper')
    ctx.recurse('midi_monitor')
    ctx.recurse('metronome')
    ctx.recurse('midi_velocity_mapper')
    ctx.recurse('cv_mapper')
    ctx.recurse('oscilloscope')
    ctx.recurse('vumeter')
