#!/usr/bin/env python

# @custom_license
#
# Taken from https://github.com/Sundin/Tome-of-Forbidden-Spells and adapted (converted the data
# files to inline Python lists).
#
# Original MIT license:
#
# Copyright (c) 2014-2019 Gustav Sundin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

beginning_phrases = [
    "Upon the Altar of *${ABS_NOUN}",
    "On the Throne of ${ABS_NOUN}",
    "...and",
    "...And justice for the",
    "...and the",
    "...with",
    "Abating the",
    "Abused in the",
    "Acts to Continue the",
    "Addicted to",
    "Addicted to the",
    "Age of",
    "And",
    "At the Sight of the",
    "Bastardized by the",
    "Be The",
    "Beneath the",
    "Boiling the",
    "Breeding the",
    "Burn The",
    "Burning the",
    "Campaign of the",
    "Carved from",
    "Closer than a",
    "Combining the",
    "Come to The",
    "Coming to The",
    "Creating the",
    "Cult of the",
    "Darken the",
    "Defacating on",
    "Desiring the",
    "Die Under the",
    "Disecting the",
    "Embracing the",
    "Enslave the",
    "Enslavement of the",
    "Enter the",
    "Evating a",
    "Excreting the",
    "Execute the",
    "Exploiting the",
    "Feasting on",
    "Feasting on the",
    "Festering with that",
    "Fight the",
    "Fighting for the",
    "Filled with",
    "Fisting the",
    "From the",
    "Frozen in the",
    "full of",
    "Holy Thunder of",
    "Immolating the",
    "Impaling the",
    "In the Prolapsed Bowels of the",
    "in the Sorrow of a",
    "Inbreeding the",
    "Incantation of the",
    "Indulging in the",
    "Infested with",
    "Infesting the",
    "Inflicted with the",
    "Influences of the",
    "Initiated by",
    "Invocation of the",
    "Invoking the",
    "Killing the",
    "Master of the",
    "Murdering the",
    "Open Arms for the",
    "Pathway of the",
    "Pathways to the",
    "Pieces of the",
    "Proclomation of the",
    "Promise of The",
    "Promise of Your",
    "Purge the",
    "Raping the",
    "Reflections of",
    "Release the",
    "Return to the",
    "Revenge Of the",
    "sacrificing the",
    "Satan's",
    "Screams for the",
    "Six Degrees Of the",
    "six Hundred and Sixty Sixth",
    "sodomizing the",
    "Sons of",
    "Spreading the",
    "Staring Through the",
    "succumbed to the",
    "Succumbing The Gates of",
    "swarming with the",
    "The Beginnings of",
    "the Birth Of",
    "the lost art of",
    "The Souls of the",
    "Thick Smoke of the",
    "Through the",
    "Thy",
    "To Die by the",
    "Trail of the",
    "Under a",
    "Under the",
    "Wearing the",
    "Worshipping the",
    "Heralding the",
]

end_phrases = [
    "Upon the Altar of ${ABS_NOUN}",
    "On the Altar of ${ABS_NOUN}",
    "Upon the Bloody Altar of ${ABS_NOUN}",
    "On the Bloody Altar of ${ABS_NOUN}",
    "at the Funeral Pyre",
    "At the Gates of Hell",
    "At the Mountains of Madness",
    "at the Shrine of Mortalities",
    "by Dogs",
    "by Fear",
    "by Hounds",
    "by Rejected Souls",
    "by the Mighty Hammer of Thor",
    "By the Stormwizard",
    "by Thor's Mighty Hammer",
    "Covered in Blood",
    "covered in Filth",
    "covering in Dirt",
    "Decay",
    "drifting to the End",
    "For Pleasure",
    "for Decadence",
    "for Eternity",
    "for Salvation",
    "For The Advanced Sadist",
    "From A Bleeding Heart",
    "From Empty Words",
    "from Mid-Gard",
    "from Middle Earth",
    "From the Dragonstar",
    "from the Lost Years",
    "from the Sea",
    "gaurded by Hounds",
    "guarded by Dogs",
    "Hiding in the Closet",
    "in Black Robes",
    "In Breathless Sleep",
    "in Brutality",
    "in Dark Faerytales",
    "in Disgust",
    "in Every Orifice",
    "in Middle Earth",
    "In Mourning",
    "In Our Quest For Satan",
    "in Pain",
    "In Quest For Satan",
    "in the Belly of the Beast",
    "in the Eyes of God",
    "in the Eyes of Satan",
    "in the Eyes of your God",
    "in the face of Satan",
    "in the face of the Devil",
    "in the Grave",
    "In the halls of Neter-khert",
    "in the Moonlight",
    "in the Pharaoh's Tomb",
    "in the Shadow",
    "In the shadow of your Black Wings",
    "in the Shadows",
    "in the shape of God",
    "in the shape of Satan",
    "in the shape of the Gods",
    "in the Vein",
    "in Valhalla",
    "in Worship of Ramses",
    "Infernous",
    "into Battle",
    "Into the Autumn Shade",
    "into the Pandemonium",
    "Made with Blood",
    "of an Enchanted Philosophy",
    "of Beherit",
    "of Black Wings",
    "of Blasphemous Horrors",
    "Of Characith",
    "of Christ",
    "Of Crimson Death",
    "Of Death",
    "of Death Sentence",
    "of Deception",
    "Of Destruction",
    "of Dreaded Deeds",
    "of Dysphoria",
    "of Evil",
    "of Evil Born",
    "Of Evil Spirits",
    "of Evil Thoughts",
    "of Existence",
    "Of Flesh",
    "of Helopolis",
    "of Infernal Legions",
    "of Infinite Malevolence",
    "of Inhumanity",
    "Of Ishtar",
    "of Jesus Christ",
    "of Jinn",
    "of Mankind",
    "of Metal",
    "of my Mystical Reign",
    "of Necrotic Tissue",
    "Of Night Primeval",
    "of Osiris",
    "Of Purest Fire",
    "of Purid Flesh",
    "of Rotting Flesh",
    "of Skulls",
    "Of Souls",
    "of Terror",
    "Of the Apocalypse Dragon",
    "Of the Appalling",
    "of the Betrayed",
    "of the Black Knowledge",
    "of the Cult",
    "of the Dark and Light",
    "of the Dead",
    "of the Empire",
    "of the Entities",
    "of the Evil One",
    "of the Firing Pits of Hell",
    "of the Frozen North",
    "of the Goat",
    "of the Half-Skull",
    "of the Heart",
    "of the Horned One",
    "of the Initiated",
    "of the Juggernaut",
    "Of the Light's Bane",
    "of the Live Autopsy",
    "of the Lost Gods",
    "of the Lost Kingdom",
    "of the Moon",
    "of the Necronomicon",
    "of the Nine-headed Serpent",
    "of the Pit",
    "of the Smoldering Corpse",
    "of the Smoldering Torso",
    "of the Squirming Cadaver",
    "of the Two-headed Goat",
    "of the Unholy Flames",
    "of the Victorium Aeternus",
    "Of the Weakening",
    "of Those Above",
    "of Time",
    "Of Tragedy",
    "of War",
    "Of Wrath",
    "of your Black Wings",
    "on cloven Hooves",
    "on Seraphim's Wings",
    "on the Altar of Humanity",
    "on the Altar of the Slaughtered",
    "on the backs of Bitch Goddess",
    "on the backs of Horned Beasts",
    "on the backs of Slutty Gods",
    "on the Banks of the Euphrates",
    "on the Bloody Altar of Humanity",
    "on the Bloody Altar of the Slaughtered",
    "on the Bloody Carcass of Christ",
    "on the Footsteps of Odin",
    "on the Funeral Pyre",
    "on the River Styx",
    "on the Seraphim",
    "on the way to hell",
    "on the wings of Night Serpents",
    "tempted by the Incubus",
    "tempted by the Succubus",
    "that are in Tattu",
    "To Remember",
    "to the Spectral Defile",
    "towards the Apocalypse",
    "towards the Armageddon",
    "trailed by the Hunter",
    "upon the Altar of Humanity",
    "upon the Altar of the ${ADJECTIVE} Goddess",
    "upon the Altar of the Slaughtered",
    "upon the Bloody Altar of Humanity",
    "upon the Bloody Altar of the Slaughtered",
    "washed in Blood",
    "whilst carried by Slaves",
    "with Pain",
    "with the Number of the Beast",
    "within the Center of the Earth",
    "within this World",
    "Written in Blood",
]

concrete_nouns = [
    "Hell",
    "Death",
    "War",
    "Plague",
    "*Storm",
    "Napalm",
    "Nightmare",
    "*Flame",
    "Flames",
    "*Night",
    "Midnight",
    "*Winter",
    "*Tornado",
    "*Shadow",
    "Power",
    "Battle",
    "*Wind",
    "Blood",
    "*Desert",
    "*Moon",
    "Thunder",
    "Rain",
    "*Fog",
    "Lightning",
    "*Midnight Moon",
    "*Forest",
    "*Sea",
    "*Vulcano",
    "*Mountain",
    "Fever",
    "Disease",
    "Witchery",
    "Venom",
    "*Corpse",
    "*Mist",
    "*Abyss",
    "*Pit",
    "*Hymn",
    "*Song",
    "*Feast",
    "Firestorm",
    "Weapons",
    "Conspiracy",
    "*Swamp",
    "Whirlwind",
    "Fireball",
    "Sorcery",
]

abstract_nouns = [
    "*Apocalypse",
    "Armageddon",
    "*Badlands",
    "Battle",
    "Blasphemy",
    "Blood",
    "Bloodshed",
    "Brimstone",
    "*Century",
    "*Coming Darkness",
    "Courage",
    "Darkness",
    "Death",
    "Destiny",
    "Destruction",
    "Doom",
    "*Earth",
    "*East",
    "Evil",
    "Fear",
    "Fire",
    "Fury",
    "Glory",
    "God",
    "Goddess",
    "*Gods",
    "*Graveyard",
    "Hatred",
    "Heresy",
    "Honour",
    "Horror",
    "Ice",
    "Iron",
    "Leather",
    "Madness",
    "Malevolence",
    "Malice",
    "Metal",
    "Might",
    "Murder",
    "Nightmare",
    "*North",
    "Pain",
    "Plutonium",
    "Power",
    "Rage",
    "Revenge",
    "Rock",
    "Shadows",
    "Slaughter",
    "Steel",
    "Stone",
    "Sulphur",
    "Termination",
    "Terror",
    "Torment",
    "Torture",
    "*Underworld",
    "Violence",
    "*Wasteland",
    "*World",
    "Wrath",
]

people = [
    "Agent",
    "Angel",
    "Avenger",
    "Bird",
    "Bringer",
    "Brother",
    "Brotherhood",
    "Champion",
    "Children",
    "Count",
    "Duke",
    "Emissary",
    "False Prophet",
    "Ghost",
    "God",
    "Guardian",
    "Hero",
    "Horseman",
    "Horsemen",
    "King",
    "Knight",
    "Lord",
    "Master",
    "Messiah",
    "Monarch",
    "Outlaw",
    "Phantom",
    "Priest",
    "Prince",
    "Prophet",
    "Rider",
    "Ruler",
    "Saviour",
    "Sinner",
    "Soldier",
    "Soldiers",
    "Son",
    "Warlord",
    "Warrior",
    "Warriors",
]

beasts = [
    "*Anaconda",
    "*Archdevil",
    "Avatar",
    "*Avenger",
    "Baal",
    "Baphomet",
    "*Basilisk",
    "*Beast",
    "*Bear",
    "Beelzebub",
    "*Behemoth",
    "Beleth",
    "Belial",
    "*Berserker",
    "*Bird",
    "*Boar",
    "*Centaur",
    "*Chimera",
    "*Cobra",
    "*Conqueror",
    "*Conquistador",
    "Construct",
    "Cthulu",
    "*Demon",
    "*Devil",
    "*Dragon",
    "*Drake",
    "*Eagle",
    "*Explorer",
    "*Fanatic",
    "*Gargoyle",
    "*Giant",
    "*Ghost",
    "*Ghoul",
    "God",
    "Goddess",
    "*Gods",
    "*Golem",
    "Hades",
    "*Hawk",
    "*Horseman",
    "*Horsemen",
    "*Hound",
    "*Hunter",
    "*Intruder",
    "*Killer",
    "*Knight",
    "Lemmy",
    "*Lion",
    "Lucifer",
    "*Lunatic",
    "*Magician",
    "*Magus",
    "*Manticore",
    "Mephisto",
    "Mephistopheles",
    "Merihem",
    "*Monk",
    "*Murderer",
    "*Necromancer",
    "*Nomad",
    "*Outlaw",
    "*Owl",
    "*Phantom",
    "*Phoenix",
    "*Pirate",
    "*Pirate Captain",
    "*Predator",
    "*Priest",
    "Raphael",
    "*Raven",
    "*Robot",
    "*Rogue",
    "Satan",
    "*Sentinel",
    "*Serpent",
    "*Shaman",
    "*Shark",
    "*Sinner",
    "*Snake",
    "*Soldier",
    "*Sorcerer",
    "*Thief",
    "*Tiger",
    "*Tormentor",
    "*Traitor",
    "*Walking Dead",
    "*Vampire",
    "*Vampire Hunter",
    "*Warrior",
    "*Werewolf",
    "*Viking",
    "*Viper",
    "*Witch Hunter",
    "*Witch",
    "*Wizard",
    "*Wolf",
    "*Wyvern",
    "Zaebos",
    "*Zombie",
    "*Nephilim",
]

items = [
    "*Sword",
    "*Crown",
    "*Church",
    "*Heart",
    "*Blade",
    "*Flames",
    "*Axe",
    "*Wheels",
    "*Mark",
    "*Portal",
    "*Talisman",
    "*Castle",
    "*Dungeon",
    "*Banner",
    "*Relic",
    "*Chainsaw",
    "*Chains",
    "*Mace",
    "*Hammer",
    "*Spear",
    "*Vortex",
    "*Storm",
    "*Grave",
    "*Machine",
    "*Tornado",
    "*Rain",
    "Witchcraft",
    "*Cult",
    "*Sect",
    "Empire",
    "Kingdom",
    "*Crucifix",
    "*Cross",
    "*Flag",
    "*Chapel",
    "*Icon",
    "*Temple",
    "*Vomit",
    "*City",
    "*Age",
    "*Reign",
    "*Chant",
    "*Chariot",
    "*Artifact",
    "*Artifacts",
    "*Book",
    "*Bible",
    "*Scroll",
    "*Sign",
    "Sixshooter",
    "*Bomb",
    "*Scythe",
    "Statue",
    "Monument",
    "*Gate",
    "*Bridge",
    "*Wall",
    "*Tower",
    "Arsenal",
    "*Hat",
    "Tome",
    "Motorcycle",
    "Bike",
    "Fist",
    "Crypt",
    "*Grimoire",
    "*Gravestone",
    "*Tombstone",
    "*Tomb",
    "*Iron Cross",
    "*Warship",
    "Age",
]

adjectives = [
    "10-pronged",
    "Abhorrent",
    "Aborted",
    "Abysmal",
    "Abyssal",
    "Acid",
    "Addicted",
    "Aggressive",
    "Anal",
    "Ancient",
    "Angelic",
    "Angry",
    "Apocalyptic",
    "Arcane",
    "Arctic",
    "Armoured",
    "Astral",
    "Atlantean",
    "Atomic",
    "Awoken",
    "Banished",
    "Barbaric",
    "Barbed",
    "Bestial",
    "Biological",
    "Black",
    "Blackened",
    "Blasphemous",
    "Bleeding",
    "Blessed",
    "Blood Red",
    "Blood Soaked",
    "Blooddrenched",
    "Bloodthirsty",
    "Bloody",
    "Bludgeon",
    "Boreal",
    "Branded",
    "Brass",
    "Breathing",
    "Brimstone",
    "Broken",
    "Brutal",
    "Brutalized",
    "Burning",
    "Burnt",
    "Cannibal",
    "Cannibalistic",
    "Carcinogenic",
    "Carnal",
    "Cataclysmic",
    "Caustic",
    "Celestial",
    "Celtic",
    "Ceremonial",
    "Chaotic",
    "Chemical",
    "Christian",
    "Clandestine",
    "Cold",
    "Colossal",
    "Constant",
    "Consumed",
    "Contaminated",
    "Corpulent",
    "Corrupted",
    "Cosmic",
    "Covered",
    "Cracked",
    "Crafted",
    "Creating",
    "Crimson",
    "Crippled",
    "Crucified",
    "Cruel",
    "Cum Soaked",
    "Cursed",
    "Damned",
    "Dark",
    "Deadly",
    "Deamon",
    "Death",
    "Decadent",
    "Decapitated",
    "Decaying",
    "Decrepid",
    "Deepest",
    "Defunct",
    "Demonic",
    "Depraved",
    "Desiring",
    "Destroyed",
    "Dethroned",
    "Diabolical",
    "Diseased",
    "Disemboweled",
    "Dismal",
    "Dismembered",
    "Distorted",
    "Divorced",
    "Drunken",
    "Dying",
    "Egyptian",
    "Electric",
    "Embossed",
    "Enchanted",
    "Endless",
    "Enemy",
    "Energized",
    "Engorged",
    "Enlightened",
    "Enthroned",
    "Epic",
    "Erotic",
    "Eternal",
    "Euphoric",
    "Everlasting",
    "Evil",
    "Eviscerated",
    "Exalted",
    "Exhumed",
    "Extreme",
    "Extremely Swollen",
    "Fallen",
    "Fatal",
    "Fatalistic",
    "Fearing",
    "Fearsome",
    "Feasting",
    "Feral",
    "Ferric",
    "Festering",
    "Finnish",
    "Flaming",
    "Flying",
    "Forbidden",
    "Forged",
    "Forgotten",
    "Fornic",
    "Forsaken",
    "Foul",
    "Freezing",
    "Frostbitten",
    "Frozen",
    "Furious",
    "Glazed",
    "Goat-headed",
    "Golgothan",
    "Gore-soaked",
    "Gory",
    "Gothic",
    "Grand",
    "Great",
    "Grim",
    "Grotesque",
    "Gruesome",
    "Gutted",
    "Gutteral",
    "Haunted",
    "Heavenly",
    "Heavy Metal",
    "Heavy",
    "Hellbent",
    "Hellish",
    "Hideous",
    "Holy",
    "Homocidal",
    "Honoured",
    "Horrible",
    "Hostile",
    "Howling",
    "Hungry",
    "Hybrid",
    "Hysteric",
    "Iced",
    "Icey",
    "Iconoclastic",
    "Immortal",
    "Infected",
    "Infernal",
    "Infested",
    "Insane",
    "Intoxicated",
    "Inverted",
    "Iron",
    "Ironclad",
    "Ironshod",
    "Lethal",
    "Long Forgotten",
    "Loyal",
    "Lunar",
    "Lurid",
    "Mad",
    "Magic",
    "Magical",
    "Magik-Filled",
    "Maimed",
    "Majestic",
    "Malevolent",
    "Malicious",
    "Malignant",
    "Maniacal",
    "Marked",
    "Masochistic",
    "Mass",
    "Massive",
    "Massive",
    "Mechanic",
    "Mechanized",
    "Medieval",
    "Mental",
    "Merciless",
    "Metal",
    "Metallic",
    "Metamorphic",
    "Midwinter",
    "Mighty",
    "Minced",
    "Misanthropic",
    "Molten",
    "Morbid",
    "Morphological",
    "Mortal",
    "Murdered",
    "Murderous",
    "Mutilated",
    "Mysterious",
    "Mystic",
    "Mystical",
    "Narcotic",
    "Necromonic",
    "Necropalic",
    "Necrophobic",
    "Necrotic",
    "New-born",
    "Nightly",
    "Nihilistic",
    "Nocturnal",
    "Nomadic",
    "Nordic",
    "Norwegian",
    "Nuclear",
    "Obscure",
    "Old",
    "Pagan",
    "Pagan",
    "Pandemic",
    "Paranoid",
    "Perpetual",
    "Pious",
    "Plagued",
    "Plutonian",
    "Plutonium",
    "Poisoned",
    "Poisonous",
    "Polar",
    "Possesed",
    "Pre-Historic",
    "Primal",
    "Primeval",
    "Psychopathic",
    "Puritanical",
    "Putrid",
    "Radioactive",
    "Raging",
    "Rain Soaked",
    "Ravenous",
    "Rebel",
    "Red",
    "Relentless",
    "Restless",
    "Ripping",
    "Rotted",
    "Rotten",
    "Rotting",
    "Sadistic",
    "Sadomasochistic",
    "Satanic",
    "Scathing",
    "Screaming",
    "Secret",
    "Seismic",
    "Shattered",
    "Silvered",
    "Sinister",
    "Skinless",
    "Slaughtered",
    "Slaytanic",
    "Sodomizing",
    "Solar",
    "Soulless",
    "Splendid",
    "Stabbed",
    "Steel",
    "Stone Throwing",
    "Stonecold",
    "Stoned",
    "Stoney",
    "Strange",
    "Subliminal",
    "Suffering",
    "Supersonic",
    "Supreme",
    "Survival",
    "Swollen",
    "Terrible",
    "Terrifying",
    "Thunder",
    "Tormented",
    "Tortured",
    "Total",
    "Toxic",
    "Tragic",
    "Transylvanian",
    "Turbulent",
    "Twilight",
    "Twisted",
    "Tyrannical",
    "Ubiquitous",
    "Unclean",
    "Undead",
    "Underground",
    "Ungodly",
    "Unhallowed",
    "Unholy",
    "Unknown",
    "Unspoken",
    "Vacant",
    "Vagrant",
    "Vampyric",
    "Vaulted",
    "Venomous",
    "Vicious",
    "Vile",
    "Vital",
    "Voltaic",
    "Vomitous",
    "Wicked",
    "Wicked",
    "Wild",
    "Winter",
    "Withered",
]

verbs = [
    "Anger",
    "Arrival",
    "Attack",
    "Bane",
    "Banner",
    "Blasphemy",
    "Blood",
    "Breath",
    "Call",
    "Castle",
    "Chant",
    "Charge",
    "City",
    "Command",
    "Corpse",
    "Cry",
    "Cult",
    "Domain",
    "Empire",
    "Flag",
    "Fury",
    "Gaze",
    "Gift",
    "Grave",
    "Hatred",
    "Heart",
    "Heresy",
    "Hunger",
    "Hunting Ground",
    "Icon",
    "Kill",
    "Kingdom",
    "Lair",
    "Last Stand",
    "Legacy",
    "Loot",
    "Madness",
    "March",
    "Mark",
    "Pact",
    "Plunder",
    "Prayer",
    "Prey",
    "Rage",
    "Rampage",
    "Return",
    "Revenge",
    "Sacrifice",
    "Scream",
    "Secret",
    "Shadow",
    "Sign",
    "Slaughter",
    "Sorrow",
    "Strike",
    "Tears",
    "Teeth",
    "Temple",
    "Toll",
    "Tomb",
    "Tooth",
    "Torment",
    "Tower",
    "Verdict",
    "Victim",
    "Warcry",
    "Wrath",
    "Disembowelment",
]

word_sets = {
    'BEG_PHRASE': beginning_phrases,
    'END_PHRASE': end_phrases,
    'CONC_NOUN': concrete_nouns,
    'ABS_NOUN': abstract_nouns,
    'PERSON': people,
    'BEAST': beasts,
    'ITEM': items,
    'ADJECTIVE': adjectives,
    'VERB': verbs,
}

sentence = [
    "Upon the Altar of *${ABS_NOUN}",
    "${ADJECTIVE} ${ABS_NOUN}",
    "${ADJECTIVE} ${CONC_NOUN}",
    "The ${ADJECTIVE} ${CONC_NOUN}",
    "${ADJECTIVE} ${PERSON} of *${ABS_NOUN}",
    "${ADJECTIVE} ${PERSON}",
    "${ADJECTIVE} ${ITEM}",
    "The ${ADJECTIVE} ${ITEM}",
    "${PERSON} of *${CONC_NOUN}",
    "The ${PERSON} of *${CONC_NOUN}",
    "*${BEAST}'s ${VERB}",
    "${ITEM} of *${CONC_NOUN}",
    "*${ITEM} of *${CONC_NOUN}",
    "${ITEM} of *${ABS_NOUN}",
    "*${ITEM} of *${ABS_NOUN}",
    "${PERSON} of *${ABS_NOUN}",
    "${ADJECTIVE} ${ITEM} of *${ABS_NOUN}",
    "${CONC_NOUN} ${ITEM}",
    "The ${CONC_NOUN} ${ITEM}",
    "${ADJECTIVE} ${BEAST}",
    "${ADJECTIVE} ${VERB}",
    "${CONC_NOUN} ${PERSON}",
    "${VERB} of the ${ITEM}",
    "${VERB} of *${BEAST}",
    "${ABS_NOUN} and ${ABS_NOUN}",
    "*${ITEM} of ${ADJECTIVE} ${ABS_NOUN}",
    "${ADJECTIVE} ${VERB} ${END_PHRASE}",
    "${BEG_PHRASE} ${ADJECTIVE} ${ADJECTIVE} ${CONC_NOUN}",
    "${BEG_PHRASE} ${CONC_NOUN} ${END_PHRASE}",
]
