# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_module('base_track_editor.py')
    #ctx.py_test('base_track_editor_test.py')
    ctx.py_module('editor.py')
    ctx.py_module('measured_track_editor.py')
    ctx.py_module('time_line.py')
    ctx.py_module('time_view_mixin.py')
    ctx.py_module('toolbox.py')
    ctx.py_module('tools.py')
    ctx.py_module('view.py')

    with ctx.group(ctx.GRP_BUILD_TESTS):
        ctx.py_module('track_editor_tests.py')
