# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_test('atom_test.py')
    #ctx.py_module('urid_mapper.pyi')
    ctx.py_test('urid_mapper_test.py')
    ctx.py_module('urid_mapper_process.py')
    ctx.py_test('urid_mapper_process_test.py')

    ctx.py_proto('urid_mapper.proto')


    # set(LIB_SRCS
    #   urid_mapper.cpp
    #   feature_manager.cpp
    # )

    # add_library(noisicaa-lv2 SHARED ${LIB_SRCS})
    # target_link_libraries(noisicaa-lv2 PRIVATE noisicaa-core)
    # target_link_libraries(noisicaa-lv2 PRIVATE noisicaa-host_system)

    # add_cython_module(core CXX)
    # target_link_libraries(${core.so} PRIVATE noisicaa-lv2)

    # add_cython_module(urid CXX)
    # target_link_libraries(${urid.so} PRIVATE noisicaa-lv2)

    # add_cython_module(options CXX)
    # target_link_libraries(${options.so} PRIVATE noisicaa-lv2)

    # add_cython_module(bufsize CXX)
    # target_link_libraries(${bufsize.so} PRIVATE noisicaa-lv2)

    # add_cython_module(worker CXX)
    # target_link_libraries(${worker.so} PRIVATE noisicaa-lv2)

    # add_cython_module(atom CXX)
    # target_link_libraries(${atom.so} PRIVATE noisicaa-lv2)

    # add_cython_module(urid_mapper CXX)
    # target_link_libraries(${urid_mapper.so} PRIVATE noisicaa-lv2)

    # add_cython_module(feature_manager CXX)
    # target_link_libraries(${feature_manager.so} PRIVATE noisicaa-lv2)
