# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_test('atom_test.py')
    ctx.py_test('urid_mapper_test.py')
    ctx.py_module('urid_mapper_process.py')
    ctx.py_test('urid_mapper_process_test.py')
    ctx.py_proto('urid_mapper.proto')
    ctx.cy_module('core.pyx', use=['noisicaa-lv2'])
    ctx.cy_module('urid.pyx', use=['noisicaa-lv2'])
    ctx.cy_module('options.pyx', use=['noisicaa-lv2'])
    ctx.cy_module('bufsize.pyx', use=['noisicaa-lv2'])
    ctx.cy_module('worker.pyx', use=['noisicaa-lv2'])
    ctx.cy_module('atom.pyx', use=['noisicaa-lv2'])
    ctx.cy_module('urid_mapper.pyx', use=['noisicaa-lv2'])
    ctx.cy_module('feature_manager.pyx', use=['noisicaa-lv2'])

    ctx.shlib(
        target='noisicaa-lv2',
        source=[
            'urid_mapper.cpp',
            'feature_manager.cpp',
        ],
        use=['NOISELIB', 'LILV', 'noisicaa-core'],
    )
