# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2017, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

import os.path


def build(ctx):
    ctx.static_file('accidental-double-flat.svg')
    ctx.static_file('accidental-double-sharp.svg')
    ctx.static_file('accidental-flat.svg')
    ctx.static_file('accidental-natural.svg')
    ctx.static_file('accidental-sharp.svg')
    ctx.static_file('duration-dot.svg')
    ctx.static_file('duration-quintuplet.svg')
    ctx.static_file('duration-triplet.svg')
    ctx.static_file('edit-beats.svg')
    ctx.static_file('edit-control-points.svg')
    ctx.static_file('edit-samples.svg')
    ctx.static_file('noisicaa-small.png')
    ctx.static_file('node-type-builtin.svg')
    ctx.static_file('node-type-ladspa.svg')
    ctx.static_file('node-type-lv2.svg')
    ctx.static_file('note-16th.svg')
    ctx.static_file('note-32th.svg')
    ctx.static_file('note-8th.svg')
    ctx.static_file('note-half.svg')
    ctx.static_file('note-quarter.svg')
    ctx.static_file('note-whole.svg')
    ctx.static_file('pointer.svg')
    ctx.static_file('rest-16th.svg')
    ctx.static_file('rest-32th.svg')
    ctx.static_file('rest-8th.svg')
    ctx.static_file('rest-half.svg')
    ctx.static_file('rest-quarter.svg')
    ctx.static_file('rest-whole.svg')
    ctx.static_file('settings_appearance.png')
    ctx.static_file('settings_audio.png')
    ctx.static_file('track-muted.svg')
    ctx.static_file('track-not-muted.svg')
    ctx.static_file('track-not-visible.svg')
    ctx.static_file('track-type-beat.svg')
    ctx.static_file('track-type-control.svg')
    ctx.static_file('track-type-group.svg')
    ctx.static_file('track-type-sample.svg')
    ctx.static_file('track-type-score.svg')
    ctx.static_file('track-visible.svg')
    ctx.static_file('warning.svg')

    for f in ctx.path.ant_glob('placeholders/*.svg'):
        ctx.static_file(f, os.path.basename(f.abspath()))
