# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2017, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.stripped_svg('accidental-double-flat.svg')
    ctx.stripped_svg('accidental-double-sharp.svg')
    ctx.stripped_svg('accidental-flat.svg')
    ctx.stripped_svg('accidental-natural.svg')
    ctx.stripped_svg('accidental-sharp.svg')
    ctx.stripped_svg('clef-c.svg')
    ctx.stripped_svg('clef-f.svg')
    ctx.stripped_svg('clef-g.svg')
    ctx.stripped_svg('duration-quintuplet.svg')
    ctx.stripped_svg('duration-triplet.svg')
    ctx.stripped_svg('note-flag-down.svg')
    ctx.stripped_svg('note-head-black.svg')
    ctx.stripped_svg('note-head-void.svg')
    ctx.stripped_svg('rest-16th.svg')
    ctx.stripped_svg('rest-32th.svg')
    ctx.stripped_svg('rest-8th.svg')
    ctx.stripped_svg('rest-half.svg')
    ctx.stripped_svg('rest-quarter.svg')
    ctx.stripped_svg('rest-whole.svg')
