# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.py_module('__init__.py')
    ctx.py_module('builtin_scanner.py')
    ctx.py_test('builtin_scanner_test.py')
    ctx.py_module('csound_scanner.py')
    ctx.py_test('csound_scanner_test.py')
    ctx.py_module('db.py')
    ctx.py_module('ladspa_scanner.py')
    ctx.py_test('ladspa_scanner_test.py')
    ctx.py_module('lv2_scanner.py')
    ctx.py_test('lv2_scanner_test.py')
    ctx.py_module('preset_scanner.py')
    ctx.py_test('preset_scanner_test.py')
    ctx.py_module('scanner.py')
