# -*- mode: python -*-

# @begin:license
#
# Copyright (c) 2015-2019, Benjamin Niemann <pink@odahoda.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# @end:license

def build(ctx):
    ctx.static_file('kick-gettinglaid.wav')
    ctx.static_file('future-thunder1.wav')
    ctx.static_file('future-thunder1.mp3')
    ctx.static_file('future-thunder1.aac')
    ctx.static_file('test1.wav')
    ctx.static_file('symbol.svg')
    ctx.rendered_csound('kick.csnd')
    ctx.rendered_csound('hihat.csnd')
    ctx.rendered_csound('snare.csnd')
    ctx.rendered_csound('organ.csnd')
    ctx.build_sf2('sf2test.yaml')

    ctx.recurse('ladspa')
    ctx.recurse('lv2/test-passthru.lv2')
    ctx.recurse('lv2/test-options.lv2')
    ctx.recurse('lv2/test-state.lv2')
    ctx.recurse('lv2/test-ui-gtk2.lv2')
